services:
  api-server:
    build:
      context: server
    image: api
    environment:
      - NODE_ENV=production
      - DB_NAME=connect
      - DB_URL_FILE=/run/secrets/db_url
    secrets:
      - db_url
    networks:
      - app-network

  proxy:
    build:
      context: .
    image: proxy
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api-server

networks:
  app-network:
    driver: bridge

secrets:
  db_url:
    environment: DB_URL
