services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - DB_NAME=connect
      - DB_URL_FILE=/run/secrets/db_url
    secrets:
      - db_url
    ports:
      - 3000:3000

secrets:
  db_url:
    environment: DB_URL
