name: check-no-todos

on:
  push

jobs:
  Check-No-TODOs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Grep for TODOs
        run: |
          if git grep TODO ; then
            echo found unadressed todo items >&2
            exit 1
          fi
