name: check-no-todos

on:
  push

jobs:
  Check-No-TODOs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Check no TODOs
        uses: DanGooding/check-no-todos-action@7a585fe4a36029a0dfa30000468df2383fc31344
